# Generated by Django 4.1.3 on 2023-02-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patches',
            fields=[
                ('PatcheId', models.AutoField(primary_key=True, serialize=False)),
                ('Cve', models.CharField(max_length=500)),
                ('Component', models.CharField(max_length=500)),
                ('BaseScore', models.CharField(max_length=500)),
            ],
        ),
    ]
